language: minimal

os: linux

dist: bionic

install:
  - ./packages/core/tools/configure.sh

script:
  - CI_CONTAINERS_WAIT_TIME=12 CI_NO_CORDA=true ./packages/core/tools/ci.sh

after_script:
  - docker ps -a
